-- =============================================================
-- PostgreSQL schema script for OFUserControlApp
-- Target: Supabase/PostgreSQL
-- =============================================================

-- Optional extension for UUID generation in DB.
-- Not required by this project because ProcesoId is generated by the app.
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================
-- Staging table for Excel users
-- =============================================================
CREATE TABLE IF NOT EXISTS "Stg_UsuariosExcel" (
    "Id" BIGSERIAL PRIMARY KEY,
    "ProcesoId" UUID NOT NULL,
    "Usuario" VARCHAR(256),
    "Correo" VARCHAR(512),
    "FuenteArchivo" VARCHAR(260) NOT NULL,
    "HashContenido" BYTEA,
    "CargadoEn" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_Stg_UsuariosExcel_Proceso" ON "Stg_UsuariosExcel" ("ProcesoId");
CREATE INDEX IF NOT EXISTS "IX_Stg_UsuariosExcel_Usuario" ON "Stg_UsuariosExcel" ("Usuario");
CREATE INDEX IF NOT EXISTS "IX_Stg_UsuariosExcel_Correo" ON "Stg_UsuariosExcel" ("Correo");
CREATE INDEX IF NOT EXISTS "IX_Stg_UsuariosExcel_CargadoEn" ON "Stg_UsuariosExcel" ("CargadoEn");

-- =============================================================
-- Cross-results table
-- =============================================================
CREATE TABLE IF NOT EXISTS "Rpt_UsuariosCruce" (
    "Id" BIGSERIAL PRIMARY KEY,
    "UsuarioExcel" VARCHAR(256),
    "CorreoExcel" VARCHAR(512),
    "EmailView" VARCHAR(512),
    "UPNView" VARCHAR(256),
    "F_Baja" VARCHAR(50),
    "Estado" VARCHAR(10) NOT NULL,
    "ProcesoId" UUID NOT NULL,
    "GeneradoEn" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_Rpt_UsuariosCruce_Proceso" ON "Rpt_UsuariosCruce" ("ProcesoId");
CREATE INDEX IF NOT EXISTS "IX_Rpt_UsuariosCruce_GeneradoEn" ON "Rpt_UsuariosCruce" ("GeneradoEn");
CREATE INDEX IF NOT EXISTS "IX_Rpt_UsuariosCruce_Estado" ON "Rpt_UsuariosCruce" ("Estado");
CREATE INDEX IF NOT EXISTS "IX_Rpt_UsuariosCruce_ProcesoEstado" ON "Rpt_UsuariosCruce" ("ProcesoId", "Estado");

-- =============================================================
-- Process log table
-- =============================================================
CREATE TABLE IF NOT EXISTS "LogProceso" (
    "Id" BIGSERIAL PRIMARY KEY,
    "ProcesoId" UUID NOT NULL,
    "Etapa" VARCHAR(50) NOT NULL,
    "Mensaje" VARCHAR(500),
    "Nivel" VARCHAR(20) NOT NULL,
    "FechaUtc" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_LogProceso_ProcesoId" ON "LogProceso" ("ProcesoId");
CREATE INDEX IF NOT EXISTS "IX_LogProceso_FechaUtc" ON "LogProceso" ("FechaUtc");

-- =============================================================
-- View_Usuarios table (Directorio Activo)
-- =============================================================
CREATE TABLE IF NOT EXISTS "View_Usuarios" (
    "Id" SERIAL PRIMARY KEY,
    "EMail" VARCHAR(512),
    "NombreCompleto" VARCHAR(512),
    "Nombre" VARCHAR(256),
    "Apellido" VARCHAR(256),
    "User_SO" VARCHAR(256),
    "F_Alta" TIMESTAMP,
    "Cod_Puesto" INT,
    "Cod_Unidad" INT,
    "Cedula" VARCHAR(50),
    "Cod_Jefe" INT,
    "COD_USUARIO_MIGRACION" INT,
    "COD_JEFE_MIGRACION" INT,
    "cod_status_usuario" INT,
    "IsAdmin" BOOLEAN,
    "IsUnidad" BOOLEAN,
    "DebeRegistrarEnTS" BOOLEAN,
    "IdStatusADAzure" INT,
    "IdAzureObject" INT,
    "F_Baja" TIMESTAMP,
    "UserPrincipalName" VARCHAR(256),
    "JobTitle" VARCHAR(256)
);

CREATE INDEX IF NOT EXISTS "IX_View_Usuarios_EMail" ON "View_Usuarios" ("EMail");
CREATE INDEX IF NOT EXISTS "IX_View_Usuarios_User_SO" ON "View_Usuarios" ("User_SO");
CREATE INDEX IF NOT EXISTS "IX_View_Usuarios_UserPrincipalName" ON "View_Usuarios" ("UserPrincipalName");
CREATE INDEX IF NOT EXISTS "IX_View_Usuarios_F_Baja" ON "View_Usuarios" ("F_Baja");

-- =============================================================
-- Stats view
-- =============================================================
CREATE OR REPLACE VIEW "vw_EstadisticasUsuarios" AS
SELECT
    "ProcesoId",
    COUNT(*) AS "TotalRegistros",
    SUM(CASE WHEN "Estado" = 'Habilitado' THEN 1 ELSE 0 END) AS "Habilitados",
    SUM(CASE WHEN "Estado" = 'Inactivo' THEN 1 ELSE 0 END) AS "Inactivos",
    MIN("GeneradoEn") AS "FechaInicio",
    MAX("GeneradoEn") AS "FechaFin"
FROM "Rpt_UsuariosCruce"
GROUP BY "ProcesoId";

-- =============================================================
-- Optional helper procedure (legacy parity)
-- The repository currently executes the cross SQL directly.
-- =============================================================
CREATE OR REPLACE PROCEDURE usp_CruzarUsuariosExcelConView(p_ProcesoId UUID)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM "Rpt_UsuariosCruce"
    WHERE "ProcesoId" = p_ProcesoId;

    INSERT INTO "Rpt_UsuariosCruce"
    (
        "UsuarioExcel",
        "CorreoExcel",
        "EmailView",
        "UPNView",
        "F_Baja",
        "Estado",
        "ProcesoId",
        "GeneradoEn"
    )
    SELECT
        s."Usuario",
        s."Correo",
        v."EMail",
        v."UserPrincipalName",
        v."F_Baja"::TEXT,
        CASE WHEN v."EMail" IS NOT NULL THEN 'Habilitado' ELSE 'Inactivo' END,
        p_ProcesoId,
        CURRENT_TIMESTAMP
    FROM "Stg_UsuariosExcel" s
    LEFT JOIN "View_Usuarios" v
           ON (s."Correo" IS NOT NULL AND s."Correo" = v."EMail")
           OR (s."Usuario" IS NOT NULL AND s."Usuario" = v."User_SO")
    WHERE s."ProcesoId" = p_ProcesoId;

    INSERT INTO "LogProceso" ("ProcesoId", "Etapa", "Mensaje", "Nivel")
    VALUES (p_ProcesoId, 'Cruce', 'Cruce completado exitosamente', 'INFO');
EXCEPTION
    WHEN OTHERS THEN
        INSERT INTO "LogProceso" ("ProcesoId", "Etapa", "Mensaje", "Nivel")
        VALUES (p_ProcesoId, 'Cruce', SQLERRM, 'ERROR');
        RAISE;
END;
$$;

-- =============================================================
-- Optional maintenance procedure
-- =============================================================
CREATE OR REPLACE PROCEDURE usp_LimpiarDatosAntiguos(p_DiasAntiguedad INT DEFAULT 30)
LANGUAGE plpgsql
AS $$
DECLARE
    v_FechaLimite TIMESTAMP;
BEGIN
    v_FechaLimite := CURRENT_TIMESTAMP - (p_DiasAntiguedad || ' days')::INTERVAL;

    DELETE FROM "Stg_UsuariosExcel" WHERE "CargadoEn" < v_FechaLimite;
    DELETE FROM "Rpt_UsuariosCruce" WHERE "GeneradoEn" < v_FechaLimite;
    DELETE FROM "LogProceso" WHERE "FechaUtc" < v_FechaLimite;
END;
$$;

